services:
  shoppingproductdb:
    container_name: shoppingproductdb
    environment:
      - POSTGRES_USER=somad
      - POSTGRES_PASSWORD=Postgres@2024!
      - POSTGRES_DB=shoppingproductdb
    restart: always
    ports:
      - 5432:5432
    volumes:
      - postgres_product:/var/lib/postgresql/data/


  shoppingbasketdb:
    container_name: shoppingbasketdb
    environment:
      - POSTGRES_USER=somad
      - POSTGRES_PASSWORD=Postgres@2024!
      - POSTGRES_DB=shoppingbasketdb
    restart: always
    ports:
      - 5433:5432
    volumes:
      - postgres_basket:/var/lib/postgresql/data/
      

  distributedcache:
    container_name: distributedcache
    restart: always
    ports:
      - "6379:6379"

  shoppingsystem.product.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_HTTPS_PORTS=8081
      - ConnectionStrings__PostGreSqlDatabase=Server=shoppingproductdb;Port=5432;Database=shoppingproductdb;UserId=somad;Password=Postgres@2024!;Include Error Detail=true
    depends_on:
      - shoppingproductdb
    ports:
      - "6000:8080"
      - "6060:8081"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro

  shoppingsystem.basket.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_HTTPS_PORTS=8081
      - ConnectionStrings__PostGreSqlDatabase=Server=shoppingbasketdb;Port=5432;Database=shoppingbasketdb;UserId=somad;Password=Postgres@2024!;Include Error Detail=true
      - ConnectionStrings__RedisConnection=distributedcache:6379
    depends_on:
      - shoppingbasketdb
      - distributedcache
    ports:
      - "6001:8080"
      - "6061:8081"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro

  shoppingsystem.discount.grpc:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_HTTPS_PORTS=8081
      - ConnectionStrings__SqliteDatabase=Data Source=shoppingdiscountdb
    ports:
      - "6002:8080"
      - "6062:8081"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro
