services:
  shoppingproductdb:
    image: postgres

  shoppingsystem.product.api:
    image: ${DOCKER_REGISTRY-}shoppingsystemproductapi
    build:
      context: .
      dockerfile: Services/Product/ShoppingSystem.Product.API/Dockerfile

volumes:
  postgres_product:

